name: vacas
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  intl: ^0.20.2
  shared_preferences: ^2.3.3
  fl_chart: ^0.70.2
  postgres: ^2.5.4
  http: ^1.3.0
  sqflite: ^2.4.2
  path: ^1.9.1
  uuid: ^4.5.1
  sqflite_common_ffi: ^2.3.5
  sqflite_common_ffi_web: ^1.0.0
  connectivity_plus: ^6.1.4
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  image_picker: ^1.1.2
  firebase_storage: ^12.4.6
  path_provider: ^2.1.5
  firebase_app_check: ^0.3.2+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Json/farm_data.json
    - assets/Json/farm.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
